// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXYw1YsjvtEMqQPuxy3lWoTWJ8WVj59Hs',
    appId: '1:329249043072:web:c6a72631b565e0026eac65',
    messagingSenderId: '329249043072',
    projectId: 'myfirst-assignment',
    authDomain: 'myfirst-assignment.firebaseapp.com',
    storageBucket: 'myfirst-assignment.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo7ru6YTYy_qeeK-shg7Y2FQWF41G22IQ',
    appId: '1:329249043072:android:e58c5561b43b9f516eac65',
    messagingSenderId: '329249043072',
    projectId: 'myfirst-assignment',
    storageBucket: 'myfirst-assignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFuXw3sb62I5SE9mKg3z6aP6oLzzPZRBQ',
    appId: '1:329249043072:ios:70cbf1c013b43f306eac65',
    messagingSenderId: '329249043072',
    projectId: 'myfirst-assignment',
    storageBucket: 'myfirst-assignment.firebasestorage.app',
    iosBundleId: 'com.example.noteBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFuXw3sb62I5SE9mKg3z6aP6oLzzPZRBQ',
    appId: '1:329249043072:ios:70cbf1c013b43f306eac65',
    messagingSenderId: '329249043072',
    projectId: 'myfirst-assignment',
    storageBucket: 'myfirst-assignment.firebasestorage.app',
    iosBundleId: 'com.example.noteBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXYw1YsjvtEMqQPuxy3lWoTWJ8WVj59Hs',
    appId: '1:329249043072:web:568c50594680beee6eac65',
    messagingSenderId: '329249043072',
    projectId: 'myfirst-assignment',
    authDomain: 'myfirst-assignment.firebaseapp.com',
    storageBucket: 'myfirst-assignment.firebasestorage.app',
  );
}
